# Generated by Django 4.2.7 on 2023-12-20 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deneme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('soru_sayisi', models.IntegerField(default=0)),
                ('sinifi', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Denemeler',
            },
        ),
        migrations.CreateModel(
            name='Ders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('sinifi', models.IntegerField(default=8)),
            ],
            options={
                'verbose_name_plural': 'Dersler',
            },
        ),
        migrations.CreateModel(
            name='GenelTaramaTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('sinifi', models.IntegerField(default=8)),
                ('soru_sayisi', models.IntegerField(default=0)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.ders')),
            ],
            options={
                'verbose_name_plural': 'Genel Tarama Testleri',
            },
        ),
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('sayfa_sayisi', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Kitaplar',
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('sinifi', models.IntegerField(default=8)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.ders')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.konu')),
            ],
            options={
                'verbose_name_plural': 'Konular',
            },
        ),
        migrations.CreateModel(
            name='Okul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Okullar',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
                ('sinifi', models.IntegerField(default=8)),
                ('soru_sayisi', models.IntegerField(default=0)),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.ders')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.konu')),
            ],
            options={
                'verbose_name_plural': 'Testler',
            },
        ),
        migrations.CreateModel(
            name='YayinEvi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Yayin Evleri',
            },
        ),
        migrations.CreateModel(
            name='Yazar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Yazarlar',
            },
        ),
        migrations.CreateModel(
            name='TestCozum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('dogru', models.IntegerField(default=0)),
                ('yanlis', models.IntegerField(default=0)),
                ('bos', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Test Çözümleri',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='yayin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.yayinevi'),
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru', models.ImageField(null=True, upload_to='')),
                ('cozum', models.ImageField(null=True, upload_to='')),
                ('yanlis', models.BooleanField(default=True)),
                ('goster', models.BooleanField(default=True)),
                ('ders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.ders')),
                ('konu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.konu')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soru_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sorular',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('tel', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('sinifi', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profilPhoto/')),
                ('grup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_grup', to='auth.group')),
                ('okulu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiller.okul')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Profiller',
            },
        ),
        migrations.CreateModel(
            name='Okuma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('sayfa', models.IntegerField(default=0)),
                ('kitap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.kitap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Okumalar',
            },
        ),
        migrations.AddField(
            model_name='kitap',
            name='yayin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.yayinevi'),
        ),
        migrations.AddField(
            model_name='kitap',
            name='yazar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.yazar'),
        ),
        migrations.CreateModel(
            name='GTTCozum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('dogru', models.IntegerField(default=0)),
                ('yanlis', models.IntegerField(default=0)),
                ('bos', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.geneltaramatest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Genel Tarama Test Sonuçları',
            },
        ),
        migrations.AddField(
            model_name='geneltaramatest',
            name='yayin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.yayinevi'),
        ),
        migrations.CreateModel(
            name='DenemeSonucu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('dogru', models.IntegerField(default=0)),
                ('yanlis', models.IntegerField(default=0)),
                ('bos', models.IntegerField(default=0)),
                ('deneme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiller.deneme')),
                ('ders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.ders')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_DenemeSonucu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Deneme Sonuçları',
            },
        ),
        migrations.AddField(
            model_name='deneme',
            name='yayin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiller.yayinevi'),
        ),
    ]
